# Status labels
- name: "status/backlog"
  color: "cfd3d7"
  description: "Not yet prioritized."
- name: "status/in-progress"
  color: "0b6e99"
  description: "Actively being worked on."
- name: "status/blocked"
  color: "d93f0b"
  description: "Cannot proceed until dependency is resolved."
- name: "status/review"
  color: "fbca04"
  description: "Ready for code review."

# Type labels
- name: "type/feature"
  color: "1d76db"
  description: "Adds new functionality."
- name: "type/bugfix"
  color: "d73a4a"
  description: "Corrects a defect."
- name: "type/refactor"
  color: "f9d0c4"
  description: "Improves structure without changing behaviour."
- name: "type/docs"
  color: "5319e7"
  description: "Documentation updates."
- name: "type/tooling"
  color: "0366d6"
  description: "Build, CI, or automation."

# Domain labels
- name: "domain/core"
  color: "0052cc"
  description: "Affects Core layer (graph, models)."
- name: "domain/services"
  color: "8a2be2"
  description: "Affects Services layer (scanning, export)."
- name: "domain/ui"
  color: "b60205"
  description: "Affects UI layer (windows, components)."
- name: "domain/ci"
  color: "6f42c1"
  description: "CI/CD or GitHub Actions."
- name: "domain/testing"
  color: "1f6feb"
  description: "Test coverage or fixtures."

# Priority labels
- name: "priority/high"
  color: "b60205"
  description: "Critical for next release."
- name: "priority/medium"
  color: "fbca04"
  description: "Important but can wait."
- name: "priority/low"
  color: "94d3a2"
  description: "Nice-to-have."

# Needs labels
- name: "needs/triage"
  color: "fef2c0"
  description: "Requires triage before work."
- name: "needs/tests"
  color: "d4c5f9"
  description: "Missing test coverage."
- name: "needs/docs"
  color: "f9bc2f"
  description: "Documentation required."
